---
title: Tidy dataset construction -- Getting and Cleaning Data
author: Cory Strope
date: April 25, 2015
output: tidyData.txt
---
 
## Project Description
Read in the data from the UCI HAR Dataset (http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones), modify the data to make a dataset, return tidy data in 'tidyData.txt'.

##Study design and data processing
 
###Collection of the raw data
Data was collected from the link:
https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

###Notes on the original (raw) data 
Some additional notes (if avaialble, otherwise you can leave this section out).
 
##Creating the tidy datafile
 
###Guide to create the tidy data file
1. Download the data
2. Merge the training and the test sets to create one data set.
3. Extract the measurements on the mean and standard deviation for each measurement. 
4. Use descriptive activity names (inactivity_labels.txt) to name the activities in the data set
5. Label the data set with descriptive variable names (in features.txt). 
6. From the data set in step 5, create a second, independent tidy data set with the average of each variable for each activity and each subject.

###Cleaning of the data
The run_analysis.R script reads in the data from several files and creates a single, tidy data set by concatenating the training and test data, adding the activity labels and features, and saving only the mean and standard deviation columns. The final tidy data reports the mean of each column, for each subject/activity data pair. 
For a more complete description, see https://github.com/cstrope/GCD_Course_Project/edit/master/README.md

##Description of the variables in the tiny_data.txt file
The final tidy data set is 180 rows by 88 columns. 

The data is separated by activity (6 activities, see README) and subject (30 subjects) rows. The remainder of the columns are the mean of each variable with the specified subject/activity pair.

The varible in the columns are as follows:
-"tBodyAcc-mean()-X"                    
-"tBodyAcc-mean()-Y"                   
-"tBodyAcc-mean()-Z"                    
-"tGravityAcc-mean()-X"                
-"tGravityAcc-mean()-Y"                 
-"tGravityAcc-mean()-Z"                
-"tBodyAccJerk-mean()-X"               
-"tBodyAccJerk-mean()-Y"               
-"tBodyAccJerk-mean()-Z"               
-"tBodyGyro-mean()-X"                  
-"tBodyGyro-mean()-Y"                  
-"tBodyGyro-mean()-Z"                  
-"tBodyGyroJerk-mean()-X"               
-"tBodyGyroJerk-mean()-Y"              
-"tBodyGyroJerk-mean()-Z"               
-"tBodyAccMag-mean()"                  
-"tGravityAccMag-mean()"                
-"tBodyAccJerkMag-mean()"              
-"tBodyGyroMag-mean()"                  
-"tBodyGyroJerkMag-mean()"             
-"fBodyAcc-mean()-X"                    
-"fBodyAcc-mean()-Y"                   
-"fBodyAcc-mean()-Z"                    
-"fBodyAcc-meanFreq()-X"               
-"fBodyAcc-meanFreq()-Y"                
-"fBodyAcc-meanFreq()-Z"               
-"fBodyAccJerk-mean()-X"                
-"fBodyAccJerk-mean()-Y"               
-"fBodyAccJerk-mean()-Z"                
-"fBodyAccJerk-meanFreq()-X"           
-"fBodyAccJerk-meanFreq()-Y"            
-"fBodyAccJerk-meanFreq()-Z"           
-"fBodyGyro-mean()-X"                   
-"fBodyGyro-mean()-Y"                  
-"fBodyGyro-mean()-Z"                   
-"fBodyGyro-meanFreq()-X"              
-"fBodyGyro-meanFreq()-Y"               
-"fBodyGyro-meanFreq()-Z"              
-"fBodyAccMag-mean()"                   
-"fBodyAccMag-meanFreq()"              
-"fBodyBodyAccJerkMag-mean()"           
-"fBodyBodyAccJerkMag-meanFreq()"      
-"fBodyBodyGyroMag-mean()"              
-"fBodyBodyGyroMag-meanFreq()"         
-"fBodyBodyGyroJerkMag-mean()"          
-"fBodyBodyGyroJerkMag-meanFreq()"     
-"tBodyAcc-std()-X"                     
-"tBodyAcc-std()-Y"                    
-"tBodyAcc-std()-Z"                     
-"tGravityAcc-std()-X"                 
-"tGravityAcc-std()-Y"                  
-"tGravityAcc-std()-Z"                 
-"tBodyAccJerk-std()-X"                 
-"tBodyAccJerk-std()-Y"                
-"tBodyAccJerk-std()-Z"                 
-"tBodyGyro-std()-X"                   
-"tBodyGyro-std()-Y"                    
-"tBodyGyro-std()-Z"                   
-"tBodyGyroJerk-std()-X"                
-"tBodyGyroJerk-std()-Y"               
-"tBodyGyroJerk-std()-Z"                
-"tBodyAccMag-std()"                   
-"tGravityAccMag-std()"                 
-"tBodyAccJerkMag-std()"               
-"tBodyGyroMag-std()"                   
-"tBodyGyroJerkMag-std()"              
-"fBodyAcc-std()-X"                     
-"fBodyAcc-std()-Y"                    
-"fBodyAcc-std()-Z"                     
-"fBodyAccJerk-std()-X"                
-"fBodyAccJerk-std()-Y"                 
-"fBodyAccJerk-std()-Z"                
-"fBodyGyro-std()-X"                    
-"fBodyGyro-std()-Y"                   
-"fBodyGyro-std()-Z"                    
-"fBodyAccMag-std()"                   
-"fBodyBodyAccJerkMag-std()"            
-"fBodyBodyGyroMag-std()"              
-"fBodyBodyGyroJerkMag-std()"           
-"angle(tBodyAccMean,gravity)"         
-"angle(tBodyAccJerkMean),gravityMean)" 
-"angle(tBodyGyroMean,gravityMean)"    
-"angle(tBodyGyroJerkMean,gravityMean)" 
-"angle(X,gravityMean)"                
-"angle(Y,gravityMean)"                  
-"angle(Z,gravityMean)"    

The variable name format is as follows (From UCI HAR Dataset descriptions):
-The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz.
-Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag).
-Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals).
-These signals were used to estimate variables of the feature vector for each pattern:
-'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

-tBodyAcc-XYZ
-tGravityAcc-XYZ
-tBodyAccJerk-XYZ
-tBodyGyro-XYZ
-tBodyGyroJerk-XYZ
-tBodyAccMag
-tGravityAccMag
-tBodyAccJerkMag
-tBodyGyroMag
-tBodyGyroJerkMag
-fBodyAcc-XYZ
-fBodyAccJerk-XYZ
-fBodyGyro-XYZ
-fBodyAccMag
-fBodyAccJerkMag
-fBodyGyroMag
-fBodyGyroJerkMag

with "mean()" or "std()" appended, depeinding on the feature value. 
Subject is an integer value specifying the subject being measured, activity is a character label specifying the activity measured; all other values are numerical.

##Sources
UCI HAR Dataset: https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip
Description: http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones 
Course Project information: https://class.coursera.org/getdata-013/human_grading/view/courses/973500/assessments/3/submissions
